package com.kd.elysian.models;
// default package

// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Review generated by hbm2java
 */
@Setter
@Getter
@Entity
@Table(name = "reviews", schema = "public")
public class Review implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @Column(name = "rating", nullable = false)
    private Integer rating;
    
    @Column(name = "comment")
    private String comment;
    
    @Column(name = "reviewer_name")
    private String reviewerName;
    
    @Column(name = "created_at", length = 29)
    private LocalDateTime createdAt;

    public Review() {
    }

    public Review(Integer id, Integer rating) {
        this.id = id;
        this.rating = rating;
    }

    public Review(Integer id, Integer rating, String comment, String reviewerName, LocalDateTime createdAt) {
        this.id = id;
        this.rating = rating;
        this.comment = comment;
        this.reviewerName = reviewerName;
        this.createdAt = createdAt;
    }

}
