package com.kd.yazpaints.models;
// default package

// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * File generated by hbm2java
 */
@Setter
@Getter
@Entity
@Table(name = "files", schema = "public")
public class File implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @Column(name = "name", nullable = false)
    private String name;

    @Column(name = "type", nullable = false)
    private String type;

    @Column(name = "location", nullable = false)
    private String location;

    public File() {
    }

    public File(Integer id, String name, String type, String location) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.location = location;
    }

}
