package com.kd.yazpaints.models;
// default package
// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final

import jakarta.persistence.*;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name="files"
    ,schema="public"
)
public class File  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String type;
     private String location;

    public File() {
    }

    public File(Integer id, String name, String type, String location) {
       this.id = id;
       this.name = name;
       this.type = type;
       this.location = location;
    }
   
    @Id 
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="type", nullable=false)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="location", nullable=false)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }




}


