package com.kd.yazpaints.models;
// default package
// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final


import jakarta.persistence.*;

/**
 * FilterData generated by hbm2java
 */
@Entity
@Table(name="filter_data"
    ,schema="public"
)
public class FilterData  implements java.io.Serializable {


     private FilterDataId id;
     private Filter filter;
     private String value;

    public FilterData() {
    }

    public FilterData(FilterDataId id, Filter filter, String value) {
       this.id = id;
       this.filter = filter;
       this.value = value;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="filterId", column=@Column(name="filter_id", nullable=false) ), 
        @AttributeOverride(name="key", column=@Column(name="key", nullable=false) ) } )
    public FilterDataId getId() {
        return this.id;
    }
    
    public void setId(FilterDataId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="filter_id", nullable=false)
    public Filter getFilter() {
        return this.filter;
    }
    
    public void setFilter(Filter filter) {
        this.filter = filter;
    }

    
    @Column(name="value", nullable=false)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


