package com.kd.yazpaints.models;
// default package

// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * FilterData generated by hbm2java
 */
@Setter
@Getter
@Entity
@Table(name = "filter_data", schema = "public")
public class FilterData implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "filterId", column = @Column(name = "filter_id", nullable = false)),
            @AttributeOverride(name = "key", column = @Column(name = "key", nullable = false)) })
    private FilterDataId id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "filter_id", insertable = false, updatable = false, nullable = false)
    private Filter filter;

    @Column(name = "value", nullable = false)
    private String value;

    public FilterData() {
    }

    public FilterData(FilterDataId id, Filter filter, String value) {
        this.id = id;
        this.filter = filter;
        this.value = value;
    }

}
