package com.kd.yazpaints.models;
// default package
// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final


import jakarta.persistence.*;

/**
 * FilterDataId generated by hbm2java
 */
@Embeddable
public class FilterDataId  implements java.io.Serializable {


     private Integer filterId;
     private String key;

    public FilterDataId() {
    }

    public FilterDataId(Integer filterId, String key) {
       this.filterId = filterId;
       this.key = key;
    }
   


    @Column(name="filter_id", nullable=false)
    public Integer getFilterId() {
        return this.filterId;
    }
    
    public void setFilterId(Integer filterId) {
        this.filterId = filterId;
    }


    @Column(name="key", nullable=false)
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FilterDataId) ) return false;
		 FilterDataId castOther = ( FilterDataId ) other; 
         
		 return ( (this.getFilterId()==castOther.getFilterId()) || ( this.getFilterId()!=null && castOther.getFilterId()!=null && this.getFilterId().equals(castOther.getFilterId()) ) )
 && ( (this.getKey()==castOther.getKey()) || ( this.getKey()!=null && castOther.getKey()!=null && this.getKey().equals(castOther.getKey()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getFilterId() == null ? 0 : this.getFilterId().hashCode() );
        result = 37 * result + ( getKey() == null ? 0 : this.getKey().hashCode() );
         return result;
   }   


}


