package com.kd.yazpaints.models;
// default package
// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final


import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Filter generated by hbm2java
 */
@Entity
@Table(name="filters"
    ,schema="public"
)
public class Filter  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<FilterData> filterDatas = new HashSet<FilterData>(0);

    public Filter() {
    }

	
    public Filter(Integer id, String name) {
        this.id = id;
        this.name = name;
    }
    public Filter(Integer id, String name, Set<FilterData> filterDatas) {
       this.id = id;
       this.name = name;
       this.filterDatas = filterDatas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="filter")
    public Set<FilterData> getFilterDatas() {
        return this.filterDatas;
    }
    
    public void setFilterDatas(Set<FilterData> filterDatas) {
        this.filterDatas = filterDatas;
    }




}


