package com.kd.yazpaints.models;
// default package

// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Filter generated by hbm2java
 */
@Setter
@Getter
@Entity
@Table(name = "filters", schema = "public")
public class Filter implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @Column(name = "name", nullable = false)
    private String name;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "filter")
    private Set<FilterData> filterDatas = new HashSet<FilterData>(0);

    public Filter() {
    }

    public Filter(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public Filter(Integer id, String name, Set<FilterData> filterDatas) {
        this.id = id;
        this.name = name;
        this.filterDatas = filterDatas;
    }

}
