package com.kd.yazpaints.models;
// default package

// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Order generated by hbm2java
 */
@Setter
@Getter
@Entity
@Table(name = "orders", schema = "public")
public class Order implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @Column(name = "full_name", nullable = false)
    private String fullName;

    @Column(name = "email", nullable = false)
    private String email;

    @Column(name = "address", nullable = false)
    private String address;

    public Order() {
    }

    public Order(Integer id, String fullName, String email, String address) {
        this.id = id;
        this.fullName = fullName;
        this.email = email;
        this.address = address;
    }

}
