package com.kd.yazpaints.models;
// default package
// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final


import jakarta.persistence.*;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,schema="public"
)
public class Order  implements java.io.Serializable {


     private Integer id;
     private String fullName;
     private String email;
     private String address;

    public Order() {
    }

    public Order(Integer id, String fullName, String email, String address) {
       this.id = id;
       this.fullName = fullName;
       this.email = email;
       this.address = address;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="full_name", nullable=false)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    
    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="address", nullable=false)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


