package com.kd.yazpaints.models;
// default package
// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final


import jakarta.persistence.*;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="products"
    ,schema="public"
)
public class Product  implements java.io.Serializable {


     private Integer id;
     private ProductType productType;
     private String name;
     private String description;
     private String price;
     private String size;

    public Product() {
    }

	
    public Product(Integer id, ProductType productType, String name, String description, String price) {
        this.id = id;
        this.productType = productType;
        this.name = name;
        this.description = description;
        this.price = price;
    }
    public Product(Integer id, ProductType productType, String name, String description, String price, String size) {
       this.id = id;
       this.productType = productType;
       this.name = name;
       this.description = description;
       this.price = price;
       this.size = size;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_id", nullable=false)
    public ProductType getProductType() {
        return this.productType;
    }
    
    public void setProductType(ProductType productType) {
        this.productType = productType;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", nullable=false)
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }

    
    @Column(name="size")
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }




}


