package com.kd.yazpaints.models;
// default package
// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final


import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductType generated by hbm2java
 */
@Entity
@Table(name="product_types"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class ProductType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Product> products = new HashSet<Product>(0);

    public ProductType() {
    }

	
    public ProductType(Integer id, String name) {
        this.id = id;
        this.name = name;
    }
    public ProductType(Integer id, String name, Set<Product> products) {
       this.id = id;
       this.name = name;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productType")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


