package com.kd.yazpaints.models;
// default package

// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Product generated by hbm2java
 */
@Setter
@Getter
@Entity
@Table(name = "products", schema = "public")
public class Product implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "type_id", nullable = false)
    private ProductType productType;

    @Column(name = "name", nullable = false)
    private String name;

    @Column(name = "description", nullable = false)
    private String description;

    @Column(name = "price", nullable = false)
    private String price;

    @Column(name = "size")
    private String size;

    public Product() {
    }

    public Product(Integer id, ProductType productType, String name, String description, String price, String size) {
        this.id = id;
        this.productType = productType;
        this.name = name;
        this.description = description;
        this.price = price;
        this.size = size;
    }

}
