package com.kd.yazpaints.models;
// default package
// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final


import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name="reviews"
    ,schema="public"
)
public class Review  implements java.io.Serializable {


     private Integer id;
     private Integer rating;
     private String comment;
     private String reviewerName;
     private LocalDateTime createdAt;

    public Review() {
    }

	
    public Review(Integer id, Integer rating) {
        this.id = id;
        this.rating = rating;
    }
    public Review(Integer id, Integer rating, String comment, String reviewerName, LocalDateTime createdAt) {
       this.id = id;
       this.rating = rating;
       this.comment = comment;
       this.reviewerName = reviewerName;
       this.createdAt = createdAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="rating", nullable=false)
    public Integer getRating() {
        return this.rating;
    }
    
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    
    @Column(name="comment")
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="reviewer_name")
    public String getReviewerName() {
        return this.reviewerName;
    }
    
    public void setReviewerName(String reviewerName) {
        this.reviewerName = reviewerName;
    }

    
    @Column(name="created_at", length=29)
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }




}


