package com.kd.yazpaints.models;
// default package
// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final


import jakarta.persistence.*;

/**
 * SiteData generated by hbm2java
 */
@Entity
@Table(name="site_data"
    ,schema="public"
)
public class SiteData  implements java.io.Serializable {


     private Integer id;
     private String cardW;
     private String cardAr;
     private String PColour;
     private String SColor;

    public SiteData() {
    }

	
    public SiteData(Integer id) {
        this.id = id;
    }
    public SiteData(Integer id, String cardW, String cardAr, String PColour, String SColor) {
       this.id = id;
       this.cardW = cardW;
       this.cardAr = cardAr;
       this.PColour = PColour;
       this.SColor = SColor;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="card_w")
    public String getCardW() {
        return this.cardW;
    }
    
    public void setCardW(String cardW) {
        this.cardW = cardW;
    }

    
    @Column(name="card_ar")
    public String getCardAr() {
        return this.cardAr;
    }
    
    public void setCardAr(String cardAr) {
        this.cardAr = cardAr;
    }

    
    @Column(name="p_colour")
    public String getPColour() {
        return this.PColour;
    }
    
    public void setPColour(String PColour) {
        this.PColour = PColour;
    }

    
    @Column(name="s_color")
    public String getSColor() {
        return this.SColor;
    }
    
    public void setSColor(String SColor) {
        this.SColor = SColor;
    }




}


