package com.kd.yazpaints.models;
// default package

// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * SiteData generated by hbm2java
 */
@Setter
@Getter
@Entity
@Table(name = "site_data", schema = "public")
public class SiteData implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;
    
    @Column(name = "card_w")
    private String cardW;
    
    @Column(name = "card_ar")
    private String cardAr;
    
    @Column(name = "p_colour")
    private String PColour;
    
    @Column(name = "s_color")
    private String SColor;

    public SiteData() {
    }

    public SiteData(Integer id) {
        this.id = id;
    }

    public SiteData(Integer id, String cardW, String cardAr, String PColour, String SColor) {
        this.id = id;
        this.cardW = cardW;
        this.cardAr = cardAr;
        this.PColour = PColour;
        this.SColor = SColor;
    }

}
