package com.kd.yazpaints.models;
// default package
// Generated 21 Jul 2025, 14:17:58 by Hibernate Tools 6.6.17.Final


import jakarta.persistence.*;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name="tags"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Tag  implements java.io.Serializable {


     private Integer id;
     private String name;

    public Tag() {
    }

    public Tag(Integer id, String name) {
       this.id = id;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


